### ISSUE TITLE
which bert's feature do you use?

### ISSUE THREAD

**Issue by mayuelala** [DirtyHarryLYL/HAKE#2]
hello,I notice that when use bert to generate feature ,there are four outputs in bert, 
1. last_hidden_state 2.pooler_output  3. hidden_state 4.attention
which bert's feature do you use ? and could you please tell me the detail of generate language feature? use which layer?

**Comment by DirtyHarryLYL** [comment]
We used the Bert model from [Huggingface](https://github.com/huggingface/transformers): 768-sized output vectors from the Bert-base.
For example:
>>> tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
>>> model = AutoModel.from_pretrained("bert-base-uncased")
>>> inputs = tokenizer("Hello world!", return_tensors="pt")
>>> outputs = model(**inputs)

We input the part name(hand), verb(hold), object name(apple) as a seq into Bert and use the output vectors.

**Comment by DirtyHarryLYL** [comment]
Usually, we beforehand extract the vectors of all text labels and use them in training. You could also import the whole Bert in the training, considering the popular CLIP, etc.

**Comment by waveboo** [comment]
Hi @DirtyHarryLYL ,
I notice that the feature vectors of the bert is 1536 dims in the `metadata/pasta_language_matrix.npy` file.
It seems two 768-sized  vectors. I'm wondering how to generate the 1536 dim vector from the AutoModel output? 
Because the AutoModel will output two types of vectors, which are (1, c, 768) dims vectors of all tokens, and (1, 768) vector of the whole seq.
Is the 1536 dim vector comes from the  [CLS] token vector concated with the vector of the whole seq? Thansk.

**Comment by silicx** [comment]
Yes, they are two concatenated 768d BERT vectors of the [CLS] feature of last_hidden_state. The two vectors are the outputs of **verb** and **object** text respectively.
